spring.application.name=quiz-service

server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

